2024-04-16 03:13:56,843 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-16 03:13:57,671 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-16 03:14:05,460 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D24BF0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:10,237 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D25CD0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:12,272 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D269C0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:14,652 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D4C110>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:16,720 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D251C0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:19,218 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D4CA40>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:21,271 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D25C70>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:23,651 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D27E30>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:26,034 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D4DA00>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:28,095 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D27E90>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:30,486 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575CFBCB0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:32,543 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D4DE50>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:34,927 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D25880>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:36,992 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D78980>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:38,124 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D4FF80>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:38,671 ERROR: Error fetching project 3 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D4C5C0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:39,371 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D27890>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:41,354 ERROR: Error fetching project 3 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D275C0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:41,747 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D4F5F0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:14:44,120 ERROR: Error fetching project 5 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014575D7A8A0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 03:15:05,878 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-16 03:15:36,604 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
