2024-04-16 02:48:34,913 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-16 02:48:35,619 INFO: Application startup [in D:\develop\vue-flask-dashboard\backend\app\__init__.py:37]
2024-04-16 02:48:37,933 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3D9250>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:48:38,150 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3DA8A0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:48:39,995 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3FCA40>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:48:42,080 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3D8B30>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:48:44,163 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3D9D90>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:48:46,220 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3FD520>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:48:48,908 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3DA1E0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:48:51,931 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3FD250>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:48:54,887 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3D9730>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:48:57,936 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3D8530>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:49:00,927 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3FE990>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:49:03,916 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3D9D90>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:49:06,925 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3D9370>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:49:09,906 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3FE810>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:49:12,916 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3D9070>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:49:15,907 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3FDFD0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:49:18,935 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3FFC80>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:49:21,909 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3D9DC0>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:49:24,913 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3FFE30>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:49:27,915 ERROR: Error fetching project 1 from external backend: HTTPConnectionPool(host='ec2-3-36-137-217.ap-northeast-2.compute.amazonaws.com', port=12345): Max retries exceeded with url: /status/1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D31B3FE420>: Failed to establish a new connection: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다')) [in D:\develop\vue-flask-dashboard\backend\app\routes.py:354]
2024-04-16 02:50:02,725 INFO: 유저 ID: <User 123@123.com> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:58]
2024-04-16 02:50:02,728 INFO: Model: <Model 1>, Dataset: <Dataset 1> [in D:\develop\vue-flask-dashboard\backend\app\routes.py:69]
